<html>
        <head>
                <title>CONFIRMATION DES RESERVATIONS</title>
        </head>
        <body>
                <h1>CONFIRMATION DES RESERVATIONS</h1>
                Votre demande a bien ete enregistree.<br/>
                Merci de bien vouloir verser la somme de 45 euros 
                sur le compte 000-000000-00 <br/>
                <input type = "submit" name = "valider" value = "Retour a 
                la page d'accueil"/>
        </body>
</html>