<html>
    <head>
        <title>PASSAGER 1</title>
    </head>
    <body>
        <h1>PASSAGER 1</h1>
     <form name = "enregistrement" methode = "post" action = "saisie.PHP">
         Nom : <input type="text" name="nom"/><br/>
         Prenom : <input type="text" name="prenom"/><br/>
         Age : <input type="text" name="age"/><br/>
     <input type="submit" name="valider" value="Etape suivante"/>
     <input type="submit" name="valider" value="Retour a la page precedente"/>
     <input type="submit" name="valider" value="Annuler reservation"/>
     </form>
    </body>
</html>